# Generated by Django 3.0.3 on 2020-02-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkmatching', '0002_auto_20200224_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='Coords',
        ),
    ]
