# Generated by Django 3.0.3 on 2020-02-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkmatching', '0003_auto_20200224_0701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultLink',
        ),
    ]
